version: '3.8'

services:

  react-extra-long-service-name-even-longer-than-you:
    labels:
      shipyard.route: '/'
    build:
      context: .
    volumes:
      - './src:/app/src'
      - './public:/app/public'
    ports:
      - '3000:3000'
